services:
  # https://github.com/kylemanna/docker-openvpn/blob/master/docs/docker-compose.md
  openvpn:
    image: kylemanna/openvpn
    cap_add:
      - NET_ADMIN
    ports:
      - 1194:1194/udp
    container_name: openvpn
    restart: always
    volumes:
      - /ssd/critical/openvpn:/etc/openvpn
      - /etc/localtime:/etc/localtime:ro
