version: '3.9'

services:
  focalboard:
    image: "mattermost/focalboard:latest"
    environment:
      VIRTUAL_HOST: "focalboard.dominik-schwaiger.ch"
      LETSENCRYPT_HOST: "focalboard.dominik-schwaiger.ch"
      VIRTUAL_PORT: "8000"
    volumes:
      - /mnt/raid5/focalboard:/opt/focalboard/data
    networks:
      - focalboard

networks:
  focalboard:
    name: focalboard
    external: true
