services:
  sunshine:
    image: lizardbyte/sunshine:latest-ubuntu-24.04
    container_name: sunshine
    restart: always
    volumes:
      - /ssd/critical/sunshine:/config
    environment:
      - TZ=Europe/Zurich
      - PUID=1001
      - PGID=1001
    ipc: host
    runtime: nvidia
    ports:
      - '47984-47990:47984-47990/tcp'
      - '48010:48010'
      - '47998-48000:47998-48000/udp'
    networks:
      - sunshine
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=sunshine"
      - "traefik.http.routers.sunshine.rule=Host(`sunshine.dominik-schwaiger.ch`)"
      - "traefik.http.routers.sunshine.tls=true"
      - "traefik.http.routers.sunshine.tls.certresolver=letsencrypt"
      - 'traefik.http.services.sunshine.loadbalancer.server.port=47990'

networks:
  sunshine:
    name: sunshine
    external: true
