services:
  registry:
    image: registry:2
    container_name: registry
    hostname: registry.dominik-schwaiger.ch
    restart: always
    networks:
      - registry-internal
    volumes:
      - /hdd/non-critical/registry/data:/var/lib/registry
      - /etc/localtime:/etc/localtime:ro
    environment:
      REGISTRY_STORAGE_DELETE_ENABLED: true
    env_file:
      - /ssd/critical/registry/secrets.env

  ui:
    image: joxit/docker-registry-ui
    container_name: registry-ui
    restart: always
    environment:
      DELETE_IMAGES: true
      REGISTRY_TITLE: Dominik's Docker Registry
      NGINX_PROXY_PASS_URL: http://registry:5000
      SINGLE_REGISTRY: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - registry
    networks:
      - registry-internal
      - registry-external
    labels:
      traefik.http.routers.registry.rule: Host(`registry.dominik-schwaiger.ch`)
      traefik.http.routers.registry.tls: true
      traefik.http.routers.registry.tls.certresolver: letsencrypt
      traefik.http.services.registry.loadbalancer.server.port: 80
      traefik.http.services.registry.loadbalancer.passHostHeader: true
      traefik.enable: true
      traefik.docker.network: registry
      traefik.http.middlewares.registry-auth.basicauth.usersfile: /ssd/critical/registry/auth/htpasswd
      traefik.http.routers.registry.middlewares: authentik@docker

networks:
  registry-internal:

  registry-external:
    name: registry
    external: true
