# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

notify:
  - name: 'email'
    platform: smtp
    sender: 'home-assistant@dominik-schwaiger.ch'
    recipient: 'mail@dominik-schwaiger.ch'
    server: 'mail.dominik-schwaiger.ch'
    username: 'home-assistant@dominik-schwaiger.ch'
    password: !secret email_password
  - platform: telegram
    name: 'Beaststation Notifications'
    chat_id: -1001816372793
  - platform: telegram
    name: 'Dominik Bot Chat'
    chat_id: 806378608

http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 0.0.0.0/0
    - 172.0.0.0/8
  auth_header:
    username_header: X-authentik-username

recorder:
  purge_keep_days: 150

telegram_bot:
  - platform: broadcast
    api_key: !secret telegram_token
    allowed_chat_ids:
      - -1001816372793 # beaststation notifications chat
      - 806378608 # bot chat dominik
