services:
  home-assistant:
    container_name: home-assistant
    hostname: home.dominik-schwaiger.ch
    image: ghcr.io/home-assistant/home-assistant:stable
    volumes:
      - /ssd/critical/home-assistant/config:/config
      - /etc/localtime:/etc/localtime:ro
    #  - /run/dbus:/run/dbus:ro
    restart: always
    #privileged: true
    #network_mode: host
    networks:
      - home-assistant
    labels:
      traefik.enable: true
      traefik.http.routers.home-assistant.rule: Host(`home.dominik-schwaiger.ch`)
      traefik.http.routers.home-assistant.tls: true
      traefik.http.routers.home-assistant.tls.certresolver: letsencrypt
      traefik.http.services.home-assistant.loadbalancer.server.port: 8123

networks:
  home-assistant:
    name: home-assistant
    external: true
