version: '3.9'

services:
  compose-watcher:
    image: "quiooo/compose-watcher"
    container_name: compose-watcher
    networks:
      - compose-watcher
    environment:
      VIRTUAL_HOST: "watcher.dominik-schwaiger.ch"
      LETSENCRYPT_HOST: "watcher.dominik-schwaiger.ch"
      INTERVAL: "-1"
      LOG: "debug"
      WEBHOOK_SECRET: "${WEBHOOK_SECRET}"
      WATCHER_TELEGRAM_TOKEN: "${WATCHER_TELEGRAM_TOKEN}"
      WATCHER_CHAT_ID: "${WATCHER_CHAT_ID}"
    env_file:
      - /etc/environment
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/domina/beaststation-docker-compose:/app/repository:rw
      - /home/domina/.ssh:/root/.ssh:ro
    restart: always

networks:
  compose-watcher:
    name: compose-watcher
    external: true
