version: '3.9'

services:
  compose-watcher:
    image: "quiooo/compose-watcher"
    networks:
      - compose-watcher
    environment:
      VIRTUAL_HOST: "watcher.dominik-schwaiger.ch"
      LETSENCRYPT_HOST: "watcher.dominik-schwaiger.ch"
      REMOTE_URL: "git@github.com:quiode/beaststation-docker-compose.git"
      INTERVAL: "-1"
      LOG: "debug"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/domina/beaststation-docker-compose:/app/repository:rw
      - /home/domina/.ssh:/root/.ssh:ro
    restart: always

networks:
  compose-watcher:
    name: compose-watcher
    external: true
