version: '3.9'

services:
  compose-watcher:
    image: "quiooo/compose-watcher"
    networks:
      - compose-watcher
    environment:
      VIRTUAL_HOST: "watcher.dominik-schwaiger.ch"
      LETSENCRYPT_HOST: "watcher.dominik-schwaiger.ch"
      INTERVAL: "-1"
      LOG: "debug"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ../../beaststation-docker-compose:/repository
      - $HOME/.ssh/id_rsa:/home/watcher/.ssh/id_rsa
      - $HOME/.ssh/id_rsa.pub:/home/watcher/.ssh/id_rsa.pub
    restart: always

networks:
  compose-watcher:
    name: compose-watcher
    external: true
