services:
  compose-watcher:
    image: "quiooo/compose-watcher"
    container_name: compose-watcher
    networks:
      - compose-watcher
    environment:
      WATCHER_INTERVAL: "-1"
      WATCHER_LOG: "info"
      WATCHER_WEBHOOK_SECRET: "${WEBHOOK_SECRET}"
      WATCHER_TELEGRAM_TOKEN: "${WATCHER_TELEGRAM_TOKEN}"
      WATCHER_CHAT_ID: "${WATCHER_CHAT_ID}"
      TZ: "Europe/Zurich"
    env_file:
      - /mnt/raid5/config/environment
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /home/domina/beaststation-docker-compose:/app/repository:rw
      - /home/domina/.ssh:/root/.ssh:ro
      - /mnt/raid5/config/environment:/etc/environment:ro
    restart: always
    labels:
      - "traefik.http.routers.watcher.rule=Host(`watcher.dominik-schwaiger.ch`)"
      - "traefik.http.routers.watcher.tls=true"
      - "traefik.http.routers.watcher.tls.certresolver=letsencrypt"
      - "traefik.enable=true"
      - "traefik.docker.network=compose-watcher"

networks:
  compose-watcher:
    name: compose-watcher
    external: true
