version: '3.9'

services:
  minecraft:
    container_name: minecraft
    ports:
      - 25565:25565
    image: "itzg/minecraft-server"
    volumes:
      - "/mnt/raid5/minecraft/server:/data"
    environment:
      EULA: "true"
      VERSION: "LATEST"
      INIT_MEMORY: "4GB"
      MAX_MEMORY: "12GB"
    tty: true
    stdin_open: true
    restart: always
  minecraft-backup:
    container_name: minecraft-backup
    image: "itzg/mc-backup"
    environment:
      BACKUP_INTERVAL: "2h"
      RCON_HOST: minecraft
      PAUSE_IF_NO_PLAYERS: "true"
      LINK_LATEST: "true"
      PRUNE_BACKUPS_DAYS: "14"
    restart: always
    volumes:
      - "/mnt/raid5/minecraft/backups:/backups"
      - "/mnt/raid5/minecraft/server:/data:ro"
