version: '3.9'

services:
  minecraft:
    container_name: minecraft
    ports:
      - 25565:25565
    image: "itzg/minecraft-server"
    volumes:
      - "/mnt/raid5/minecraft/server:/data"
    environment:
      EULA: "true"
      VERSION: "LATEST"
      MEMORY: "8G"
    tty: true
    stdin_open: true
    restart: always
