log:
  level: "INFO"

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false

  file:
    filename: "/traefik-provider.yml"

global:
  sendAnonymousUsage: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
    transport:
      respondingTimeouts:
        readTimeout: "5m"

  websecure:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: "5m"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "mail@dominik-schwaiger.ch"
      storage: "acme.json"
      httpChallenge:
        entryPoint: "web"
