services:
  nextcloud:
    image: "nextcloud:production-apache"
    restart: always
    container_name: nextcloud
    depends_on:
      - nextcloud-database
      - nextcloud-cache
    networks:
      - nextcloud-extern
      - nextcloud-intern
    environment:
      MYSQL_DATABASE: "nextcloud"
      MYSQL_USER: "nextcloud"
      MYSQL_PASSWORD: "${DB_PW}"
      MYSQL_HOST: "nextcloud-database"
      NEXTCLOUD_ADMIN_USER: "admin"
      NEXTCLOUD_ADMIN_PASSWORD: "${NEXTCLOUD_ADMIN_PASSWORD}"
      REDIS_HOST: "nextcloud-cache"
      APACHE_DISABLE_REWRITE_IP: "1"
      TRUSTED_PROXIES: "192.168.90.0/24"
      OVERWRITEHOST: "nextcloud.dominik-schwaiger.ch"
      OVERWRITEPROTOCOL: "https"
      OVERWRITEWEBROOT: "/"
      NEXTCLOUD_TRUSTED_DOMAINS: "nextcloud.dominik-schwaiger.ch"
      SMTP_HOST: "dominik-schwaiger.vsos.ethz.ch"
      SMTP_SECURE: "ssl"
      SMTP_NAME: "nextcloud@dominik-schwaiger.ch"
      SMTP_PORT: "465"
      SMTP_PASSWORD: "${NEXTCLOUD_SMTP_PASSWORD}"
      MAIL_FROM_ADDRESS: "nextcloud"
      MAIL_DOMAIN: "dominik-schwaiger.ch"
    volumes:
      - nextcloud:/var/www/html
      - /mnt/raid5/nextcloud/data:/var/www/html/data
      - /mnt/raid5/nextcloud/apps:/var/www/html/custom_apps
      - /mnt/raid5/nextcloud/config:/var/www/html/config
      - /mnt/raid5/nextcloud/themes:/var/www/html/themes
    labels:
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.dominik-schwaiger.ch`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=letsencrypt"
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"
      - "traefik.http.middlewares.nextcloud-header.headers.framedeny=true"
      - "traefik.http.middlewares.nextcloud-header.headers.browserxssfilter=true"
      - "traefik.http.middlewares.nextcloud-header.headers.stsSeconds=63072000"
      - "traefik.http.middlewares.nextcloud-header.headers.customFrameOptionsValue=SAMEORIGIN"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-header@docker"
      - "traefik.http.routers.nextcloud.middlewares=nextcloud_redirectregex@docker"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.permanent=true"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.regex=https://(.*)/.well-known/(?:card|cal)dav"
      - "traefik.http.middlewares.nextcloud_redirectregex.redirectregex.replacement=https://$${1}/remote.php/dav"
      - "traefik.enable=true"

  # cron job to allow nextcloud to use cron (instead of custom image https://github.com/nextcloud/docker/blob/master/.examples/docker-compose/insecure/mariadb/apache/docker-compose.yml)
  nextcloud-cron:
    image: "nextcloud:production-apache"
    restart: always
    container_name: nextcloud-cron
    volumes:
      - nextcloud:/var/www/html
      - /mnt/raid5/nextcloud/data:/var/www/html/data
      - /mnt/raid5/nextcloud/apps:/var/www/html/custom_apps
      - /mnt/raid5/nextcloud/config:/var/www/html/config
      - /mnt/raid5/nextcloud/themes:/var/www/html/themes
    entrypoint: /cron.sh
    networks:
      - nextcloud-intern
    depends_on:
      - nextcloud

  # onlyoffice: # TODO: doesn't currently work :c
  #   image: "onlyoffice/documentserver"
  #   container_name: onlyoffice
  #   restart: always
  #   networks:
  #     - onlyoffice
  #     - nextcloud-intern
  #   environment:
  #     JWT_SECRET: "${JWT_SECRET}"
  #     ONLYOFFICE_HTTPS_HSTS_ENABLED: "false"
  #     JWT_ENABLED: "false"
  #   labels:
  #     - "traefik.http.routers.office.rule=Host(`office.dominik-schwaiger.ch`)"
  #     - "traefik.http.routers.office.tls=true"
  #     - "traefik.http.routers.office.tls.certresolver=letsencrypt"
  #     - "traefik.enable=true"

  nextcloud-database:
    image: "mariadb:lts"
    container_name: nextcloud-database
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: "${DB_PW}"
      MARIADB_DATABASE: "nextcloud"
      MARIADB_USER: "nextcloud"
      MARIADB_PASSWORD: "${DB_PW}"
      MARIADB_AUTO_UPGRADE: 1
    networks:
      - nextcloud-intern
    volumes:
      - /mnt/raid5/nextcloud/database:/var/lib/mysql

  nextcloud-cache:
    image: "redis:alpine"
    container_name: nextcloud-cache
    restart: always
    networks:
      - nextcloud-intern

volumes:
  nextcloud:

networks:
  nextcloud-extern:
    name: nextcloud
    external: true

  nextcloud-intern:

  onlyoffice:
    name: onlyoffice
    external: true
