services:
  bitwarden:
    image: bitwarden/self-host:2024.9.2-beta #TODO: reinstall docker compose when stable version releases
    container_name: bitwarden
    env_file:
      - /run/agenix/nextcloud_smtp_password
      - /run/agenix/bw_installation_id
      - /run/agenix/bw_installation_key
      - settings.env
    environment:
      TZ: 'Europe/Zurich'
    depends_on:
      - bitwarden-db
    restart: always
    volumes:
      - /ssd/critical/bitwarden/data:/etc/bitwarden
      - /hdd/non-critical/bitwarden/logs:/var/log/bitwarden
    networks:
      - bitwarden-internal
      - bitwarden-external
    labels:
      - 'traefik.http.routers.bitwarden.rule=Host(`bitwarden.dominik-schwaiger.ch`)'
      - 'traefik.http.routers.bitwarden.tls=true'
      - 'traefik.http.routers.bitwarden.tls.certresolver=letsencrypt'
      - 'traefik.http.services.bitwarden.loadbalancer.server.port=8080'
      - 'traefik.enable=true'
      - 'traefik.docker.network=bitwarden'

  bitwarden-db:
    image: mariadb:lts
    container_name: bitwarden-db
    environment:
      MARIADB_USER: 'bitwarden'
      MARIADB_PASSWORD: 'super_strong_password' # TODO: use the db password
      MARIADB_DATABASE: 'bitwarden_vault'
      MARIADB_RANDOM_ROOT_PASSWORD: 'true'
      MARIADB_AUTO_UPGRADE: 1
      TZ: 'Europe/Zurich'
    restart: always
    volumes:
      - /ssd/critical/bitwarden/database:/var/lib/mysql
    networks:
      - bitwarden-internal

networks:
  bitwarden-internal:
    name: 'bitwarden-internal'

  bitwarden-external:
    name: 'bitwarden'
    external: true
