services:
  atuin:
    restart: always
    image: ghcr.io/atuinsh/atuin
    command: server start
    networks:
      - atuin-internal
      - atuin-external
    volumes:
      - /mnt/raid5/atuin/config:/config
    environment:
      ATUIN_HOST: '0.0.0.0'
      ATUIN_OPEN_REGISTRATION: 'true'
      ATUIN_DB_URI: postgres://atuin:${ATUIN_DB_PASSWORD}@db/atuin
      RUST_LOG: info,atuin_server=debug
      TZ: Europe/Zurich
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=atuin"
      - "traefik.http.routers.atuin.rule=Host(`atuin.dominik-schwaiger.ch`)"
      - "traefik.http.routers.atuin.tls=true"
      - "traefik.http.routers.atuin.tls.certresolver=letsencrypt"
      #- 'traefik.http.services.atuin.loadBalancer.server.port=8888'

  db:
    image: postgres
    restart: always
    networks:
      - atuin-internal
    volumes:
      - /mnt/raid5/atuin/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: atuin
      POSTGRES_PASSWORD: ${ATUIN_DB_PASSWORD}
      POSTGRES_DB: atuin
      TZ: Europe/Zurich

networks:
  atuin-internal:

  atuin-external:
    name: atuin
    external: true
