services:
  runner:
    image: gitlab/gitlab-runner
    container_name: gitlab-runner
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/raid5/gitlab-runner/config:/etc/gitlab-runner