services:
  stationboard:
    image: quiooo/stationboard
    container_name: stationboard
    restart: always
    networks:
      - stationboard
    environment:
      VIRTUAL_HOST: "stationboard.dominik-schwaiger.ch"
      LETSENCRYPT_HOST: "stationboard.dominik-schwaiger.ch"
      VIRTUAL_PORT: "80"

networks:
  stationboard:
    name: stationboard
    external: true