version: '3.9'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:1.2-alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    networks:
      - nextcloud
    volumes:
      - conf:/etc/nginx/conf.d
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy"
    restart: always

  acme-companion:
    image: nginxproxy/acme-companion:2.2
    container_name: nginx-proxy-acme
    depends_on:
      - nginx-proxy
    environment:
      - DEFAULT_EMAIL=mail@dominik-schwaiger.ch
    volumes:
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - certs:/etc/nginx/certs
      - acme:/etc/acme.sh
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always

  watchtower:
    image: "containrrr/watchtower"
    command: --cleanup --interval 3600
    environment:
      REPO_USER: "quiooo"
      REPO_PASSWORD: "${DOCKER_PW}"
      WATCHTOWER_NOTIFICATION_URL: "telegram://${TELEGRAM_WATCHTOWER_TOKEN}@telegram?chats=806378608%2C-1001816372793&preview=No"
      WATCHTOWER_NOTIFICATION_REPORT: "true"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always

volumes:
  conf:
  vhost:
  html:
  certs:
  acme:

networks:
  nextcloud:
    name: nextcloud
