services:
  website:
    image: quiooo/dominik-schwaiger.ch
    container_name: dominik-schwaiger.ch
    restart: always
    networks:
      - dominik-schwaiger
    environment:
      VIRTUAL_HOST: "dominik-schwaiger.ch"
      LETSENCRYPT_HOST: "dominik-schwaiger.ch"

networks:
  dominik-schwaiger:
    name: dominik-schwaiger
    external: true
