services:
  website:
    image: quiooo/dominik-schwaiger.ch
    container_name: dominik-schwaiger.ch
    networks:
      - dominik-schwaiger
    environment:
      VIRTUAL_HOST: "dominik-schwaiger.ch"
      LETSENCRYPT_HOST: "dominik-schwaiger.ch"
    volumes:
      - /mnt/raid5/dominik-schwaiger.ch/images:/dominik-schwaiger.ch/images
    env_file:
      - /etc/environment

networks:
  dominik-schwaiger:
    name: dominik-schwaiger
    external: true
