version: "3.9"

services:
  portainer:
    image: "portainer/portainer-ce:alpine"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/raid5/portainer/data:/data
    environment:
      VIRTUAL_HOST: "portainer.dominik-schwaiger.ch"
      LETSENCRYPT_HOST: "portainer.dominik-schwaiger.ch"
      VIRTUAL_PORT: "9000"
    container_name: portainer
    restart: always

networks:
  portainer:
    name: portainer
    external: true
