services:
  watchtower:
    image: "containrrr/watchtower"
    container_name: watchtower
    restart: always
    command: --cleanup --schedule "0 0 3 * * *"
    environment:
      REPO_USER: "quiooo"
      REPO_PASSWORD: "${DOCKER_PW}"
      WATCHTOWER_NOTIFICATION_URL: "telegram://${TELEGRAM_WATCHTOWER_TOKEN}@telegram?chats=806378608%2C-1001816372793&preview=No"
      WATCHTOWER_NOTIFICATION_REPORT: "true"
      TZ: "Europe/Zurich"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro