services:
  wolf:
    container_name: wolf
    image: ghcr.io/games-on-whales/wolf:stable
    environment:
      - XDG_RUNTIME_DIR=/tmp/sockets
      - HOST_APPS_STATE_FOLDER=/etc/wolf
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - TZ=Europe/Zurich
    volumes:
      - /hdd/non-critical/wolf:/etc/wolf
      - /tmp/sockets:/tmp/sockets
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/:/dev/
      - /run/udev:/run/udev
    device_cgroup_rules:
      - 'c 13:* rmw'
    devices:
      - /dev/dri
      - /dev/uinput
      - /dev/uhid
    runtime: nvidia
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - capabilities: [gpu]
    networks:
      - wolf
    ports:
      # HTTPS
      - 47984:47984/tcp
      # HTTP
      - 47989:47989/tcp
      # Control
      - 47999:47999/udp
      # RTSP
      - 48010:48010/tcp
      # Video (up to 10 users, you can open more ports if needed)
      - 48100-48110:48100-48110/udp
      # Audio (up to 10 users, you can open more ports if needed)
      - 48200-48210:48200-48210/udp
    restart: always
    labels:
    - "traefik.enable=true"
    - "traefik.docker.network=wolf"
    - "traefik.http.routers.wolf.rule=Host(`wolf.dominik-schwaiger.ch`)"
    - "traefik.http.routers.wolf.tls=true"
    - "traefik.http.routers.wolf.tls.certresolver=letsencrypt"
    - 'traefik.http.services.wolf.loadbalancer.server.port=47989'
  
networks:
  wolf:
    name: wolf
    external: true