services:
  wolf:
    image: ghcr.io/games-on-whales/wolf:stable
    environment:
      - XDG_RUNTIME_DIR=/tmp/sockets
      - HOST_APPS_STATE_FOLDER=/etc/wolf
      - NVIDIA_DRIVER_CAPABILITIES=all
      - NVIDIA_VISIBLE_DEVICES=all
      - TZ=Europe/Zurich
    volumes:
      - /hdd/non-critical/wolf:/etc/wolf
      - /tmp/sockets:/tmp/sockets
      - /var/run/docker.sock:/var/run/docker.sock
      - /dev/:/dev/
      - /run/udev:/run/udev
    device_cgroup_rules:
      - 'c 13:* rmw'
    devices:
      - /dev/dri
      - /dev/uinput
      - /dev/uhid
    runtime: nvidia
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - capabilities: [gpu]
    ports:
      # HTTPS
      - 47984:47984
      # HTTP
      - 47989:47989
      # Control
      - 47999:47999
      # RTSP
      - 48010:48010
      # Video (up to 10 users, you can open more ports if needed)
      - 48100-48110:48100-48110
      # Audio (up to 10 users, you can open more ports if needed)
      - 48200-48210:48200-48210
    restart: always