services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
    volumes:
      - /ssd/critical/qbittorrent/appdata:/config
      - /hdd/non-critical/qbittorrent/downloads:/downloads
      - /etc/localtime:/etc/localtime:ro
    restart: always
    networks:
      - qbittorrent
    labels:
      traefik.http.routers.qbittorrent.rule: Host(`qbittorrent.dominik-schwaiger.ch`)
      traefik.http.routers.qbittorrent.tls: true
      traefik.http.routers.qbittorrent.tls.certresolver: letsencrypt
      traefik.http.services.qbittorrent.loadbalancer.server.port: 8080
      traefik.enable: true
      traefik.docker.network: qbittorrent

networks:
  qbittorrent:
    name: qbittorrent
    external: true
