log:
  level: "DEBUG"

api:
  dashboard: true

providers:
  docker:
    exposedByDefault: false

global:
  sendAnonymousUsage: true

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "websecure"
          scheme: "https"
    transport:
      respondingTimeouts:
        readTimeout: "15m"
        writeTimeout: "15m"
        idleTimeout: "15m"

  websecure:
    address: ":443"
    transport:
      respondingTimeouts:
        readTimeout: "15m"
        writeTimeout: "15m"
        idleTimeout: "15m"

certificatesResolvers:
  letsencrypt:
    acme:
      email: "mail@dominik-schwaiger.ch"
      storage: "acme.json"
      httpChallenge:
        entryPoint: "web"
